//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giveaway
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public giveaway()
        {
            this.skins_in_giveaway1 = new HashSet<skins_in_giveaway>();
            this.users = new HashSet<user>();
            this.users_in_giveaway1 = new HashSet<users_in_giveaway>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public Nullable<int> fk_skinsInGiveaway { get; set; }
        public Nullable<int> fk_usersInGiveaway { get; set; }
    
        public virtual skins_in_giveaway skins_in_giveaway { get; set; }
        public virtual users_in_giveaway users_in_giveaway { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skins_in_giveaway> skins_in_giveaway1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users_in_giveaway> users_in_giveaway1 { get; set; }
    }
}
