//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSGO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<betting> bettings { get; set; }
        public virtual DbSet<evaluation> evaluations { get; set; }
        public virtual DbSet<eventt> eventts { get; set; }
        public virtual DbSet<giveaway> giveaways { get; set; }
        public virtual DbSet<match> matches { get; set; }
        public virtual DbSet<place> places { get; set; }
        public virtual DbSet<player> players { get; set; }
        public virtual DbSet<program> programs { get; set; }
        public virtual DbSet<skin> skins { get; set; }
        public virtual DbSet<skins_in_giveaway> skins_in_giveaway { get; set; }
        public virtual DbSet<team> teams { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<tournament> tournaments { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<users_bets> users_bets { get; set; }
        public virtual DbSet<users_in_giveaway> users_in_giveaway { get; set; }
    }
}
