//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_bet_skins
    {
        public int id { get; set; }
        public Nullable<bool> won { get; set; }
        public Nullable<int> fk_user { get; set; }
        public Nullable<int> fk_betting { get; set; }
        public Nullable<int> fk_skin { get; set; }
    
        public virtual betting betting { get; set; }
        public virtual skin skin { get; set; }
        public virtual user user { get; set; }
    }
}
